### ISSUE TITLE
App Crash after subscribing to channel

### ISSUE THREAD

**Issue by Moussawi7** [pusher/pusher-js#103]
Hi @pl,
I have a chat mobile application(using cordova) that use pusher to serve messages,
the application is working excellent on android devices, and IOS 7-, but it crash on IOS8.
After debugging i discovered that when i subscribe to a channel and use (Sqlite plugin)[www.github.com/brodysoft/Cordova-SQLitePlugin] in the same time, the application crash.
Therefore, i think that they use the same ports...
Did you hear about this issue before!!. and please let me know about the ports used by pusher-js.
Thank you.

**Comment by pl** [comment]
Hi,

I don't think SQLite uses the same ports as Pusher - normally pusher-js connects to 80 for unencrypted connections and 443 for encrypted ones.

I'm not a specialist in iOS development, it might be an issue with the SQLite plugin or Cordova - they contain native code and are first suspects for me. JS code should not really crash applications. It's hard to tell where the problem is.

Maybe a dirty hack is to try calling SQLite and Pusher functions in separate ticks (using `setTimeout` with 0 timeout). You can try that to see if it helps, but it's a really ugly solution (horrible flow control, possible race conditions) and I'd rather not have such code in a production app ;)

**Comment by Moussawi7** [comment]
Hi @pl ,
First thank you for you help.
As you said "*** JS code should not really crash applications***", and for this reason i spent around 3 hours to discover the reason of the issue.
anyway, your trick work for me, so thank you for your help(you are always helpful).

**Comment by machty** [comment]
Related: https://issues.apache.org/jira/browse/CB-9102

I just fixed this bug in my app: it happens if, within the same event loop that you handle a pusher callback (or any callback that ultimately originates from a native WebSocket event), you make a call through cordova back into native code. It is "fixed" by setting a JS timeout before handling the event.

@pl integrating Pusher with Cordova (or a Cordova-like environment) is very common, and this bug is tricky and misleading enough that it might be beneficial to just build the setTimeout into the pusher JS lib to prevent these issues from happening in the first place. I don't think this would affect user apps in any way, whether it be timing or performance. And FWIW it would probably have to be a timer, and not anything tricky like using MutationObservers to do a next tick.

**Comment by ituhin** [comment]
@machty how did you integrate pusher for push notifications in your cordova app ?
is there a javascript client lib to register device push tokens with pusher channels ?
or did you write one yourself ?

**Comment by hph** [comment]
@machty For now I think this issue will be enough for anyone that runs into a similar problem, but I think you raised a good point and we will look into implementing that in the future.
