### ISSUE TITLE
Shorter code

### ISSUE THREAD

**Issue by aMarCruz** [pusher/pusher-js#107]
In https://github.com/pusher/pusher-js/blob/master/src/util.js#L3 ...
why not pre-built functions?
```javascript
  now: Date.now || function(){ return +new Date(); },
```
this is shorter, more efficient code, and still compatible, w/o micro-optimization avoid test for Date.now in each call.
The same in stringify, arrayIndexOf, ...etc.

**Comment by leggetter** [comment]
These functions have potentially existed since 2011 when the library was first created. So, I'm not sure of the reasoning behind the existence of them, why they're formed in the way they or, or the necessity of some of them now given us recently dropping IE6. We do run code coverage as part of tests so hopefully there isn't any dead code.

Please do submit a pull request if you feel you can improve things. We would prefer clear code even if it's slightly verbose.

**Comment by aMarCruz** [comment]
Thanks @leggetter, the above definition seems more clear to me, and it is ES3 compatible (IE6+).
Anyway, we need a service like Pusher, with the lightweight possible code, for desktop & mobile.
I will study the code.

**Comment by leggetter** [comment]
Thanks, @aMarCruz. Hopefully your evaluation goes well. I'll close this issue for now.
