### ISSUE TITLE
websockets fallback to an encrypted protocol when the user instantiates with encrypted=false

### ISSUE THREAD

**Issue by edwardotis** [pusher/pusher-js#147]
Unless I misunderstand, the user has specifically said that the client should _not_ try to use encryption. In my case, my local development websockets server does not support wss.

As I dig into a connection error 1006 bug in Chrome, I see that pusher client is falling back to use secure websockets protocol. This will always fail. Meanwhile, the encrypted loop does not use secure websockets to fallback? It should be the opposite, right?

Furthermore, the encrypted http fallback should be using https, not http, right?

https://github.com/pusher/pusher-js/commit/b19e8d8cbec7695ce0bd005eed9277c7f5f2af93

```
+    var wsStrategy;
 +    if (config.encrypted) {
 +      wsStrategy = [
 +        ":best_connected_ever",
 +        ":ws_loop",
 +        [":delayed", 2000, [":http_fallback_loop"]]
 +      ];
 +    } else {
 +      wsStrategy = [
 +        ":best_connected_ever",
 +        ":ws_loop",
 +        [":delayed", 2000, [":wss_loop"]],
 +        [":delayed", 5000, [":http_fallback_loop"]]
 +      ];
 +    }
```

**Comment by hph** [comment]
Hi @edwardotis and apologies for the delay in replying to your question here.

With `encrypted: false`, Pusher will try to connect with these transports (in the following order):

1) `ws`
2) `wss`
3) `xhr_streaming`
4) `xhr_polling`

With `encrypted: true`, Pusher will skip trying `ws` and instead try these transports:

1) `wss`
2) `xhr_streaming`
3) `xhr_polling`

The main reason for trying `wss` after `ws` when encrypted is set to false or not specified is that unencrypted websockets tend to get interrupted by proxies, but they are cheaper than encrypted ones. This is not necessary when `encrypted` is set to `true` and Pusher will try `wss` straight away.

You can check this yourself by creating an HTML file with the following contents and opening it in your browser and refreshing after disconnecting from the network. Change the value of `encrypted` to see the different behaviours. Note that you must open it while connected to a network in the first request, since it loads the library from an external host.

```html
<script src="https://unpkg.com/pusher-js"></script>
<script>
Pusher.logToConsole = true;
Pusher.log = message => {
  const p = document.createElement('p');
  p.innerText = message;
  document.body.appendChild(p);
}

const socket = new Pusher('00a06d69777405536699', {
  cluster: 'mt1',
  encrypted: true,
});
</script>
```
