### ISSUE TITLE
Avoid Global Namespace

### ISSUE THREAD

**Issue by thetutlage** [pusher/pusher-js#158]
I developed an embeddable widget which makes use of Pusher. Pusher is required from [npm](https://www.npmjs.com/package/pusher-js) and my final js file is bundled using `browserify`.

As Pusher makes use of `window.Pusher` it is creating conflicts when the page using my widget is already making use of Pusher.

**Comment by jackfranklin** [comment]
We should probably only export onto the window if there's nothing there already.

@jpatel531 what do you think?

**Comment by thetutlage** [comment]
But when if the global Pusher version is something different from the one bundled using require js.

So in my example the 3rd party website was using pusher `2.2` and i built my widget using `3.0`. When my widget loaded it added `3.0` to the global scope and their Pusher code failed as they are dependent upon something from `2.2`.

**Comment by jackfranklin** [comment]
There's only so much we can do here; we need Pusher to be globally available because a lot of people use us in that manner. What I've done in my own code is make my widgets take an instance of Pusher as an argument, and then you don't need your widget to bundle Pusher.

I also would encourage you to upgrade to v3 too as it's a fairly large improvement.

Additionally, the issues of managing different versions of Pusher on the same page isn't something we're able to easily fix.

**Comment by thetutlage** [comment]
Okay, make sense. Thanks for quick response

**Comment by jpatel531** [comment]
+1 @jackfranklin

**Comment by mgalgs** [comment]
I just ran into this issue due to [the Freshdesk Live Chat widget](https://freshdesk.com/multichannel-support/live-chat) bundling its own copy of Pusher.

> we need Pusher to be globally available because a lot of people use us in that manner.

Yes, you don't want to break backwards compatibility, but couldn't there be an optional "noconflict" mode?  Something like [`jQuery.noConflict()`](https://api.jquery.com/jquery.noconflict/).

> What I've done in my own code is make my widgets take an instance of Pusher as an argument, and then you don't need your widget to bundle Pusher.

But what if you don't control the widget (as is the case for me with the Freshdesk widget)?

**Comment by hot-leaf-juice** [comment]
I haven't tested this myself yet so ymmv, but you might have some luck bundling the node build of pusher-js with webpack or something similar, and then importing it under some other name. e.g. something like

    let Pusher2 = require("pusher-js/node");

As far as I'm aware the "node" version doesn't actually rely on any runtimes, and the main difference is just the module definition format, so the above should work in the browser.

**Comment by mgalgs** [comment]
@hot-leaf-juice no luck... :(  It doesn't really work since `require` on the browser is async (has to be called with `require([module], callback)`), but the pusher node module is using the sync `require(module)` version, so I see stuff like:

```
Uncaught Error: Module name "faye-websocket" has not been loaded yet for context: _. Use require([])
http://requirejs.org/docs/errors.html#notloaded
```

**Comment by jpatel531** [comment]
@mgalgs - could you try the worker build (`pusher-js/worker`)? This will work readily in the browser and does not (if memory serves) attach itself to the global namespace. The caveat is that it uses fetch for auth requests + sending stats to Pusher. This means on some older browsers (IE ≤ 11) and Safari, it will require a polyfill: <https://github.com/github/fetch>.

**Comment by hot-leaf-juice** [comment]
@jpatel531 how would you actually go about doing this? Just importing `https://js.pusher.com/4.0/pusher.worker.min.js` instead of `https://js.pusher.com/4.0/pusher.min.js` still attaches to `window.Pusher` (thanks for your input by the way!)

**Comment by jpatel531** [comment]
mmm that's probably because using a script tag will attach variables to the global scope. if you try to import it using a module system (e.g. webpack etc.) it won't be available globally.

```js
const Pusher2 = require('pusher-js/worker');
// etc.
```

**Comment by hot-leaf-juice** [comment]
I couldn't get this to work with a bundling system (`require("pusher-js/worker")` doesn't appear to be a thing...) but if you go ahead and import `pusher.worker.min.js` in a script tag then you can rename `window.Pusher` to `window.Pusher2` and everything works swimmingly.

(you can't do the same with plain pusher-js because for some reason it references things in `window.Pusher` and then complains when it can't find it.)

**Comment by mgalgs** [comment]
> if you go ahead and import pusher.worker.min.js in a script tag then you can rename window.Pusher to window.Pusher2 and everything works swimmingly.

Yep, that worked!  Thanks for the workaround.  I'll be on the lookout for a more permanent solution.
