### ISSUE TITLE
CSP issue with 3.1 in Chrome extension background context

### ISSUE THREAD

**Issue by georgehenderson** [pusher/pusher-js#168]
Ran into an issue with the latest release today. In a chrome extension context eval of any form is not allowed by default. This causes a problem with how you find the global object.

The offending line of code is [here](https://github.com/pusher/pusher-js/blob/7d4160038b5836163af2bdc23aabce6219a9c242/src/core/base64.ts#L1)

```
var global = Function("return this")();
```

There is a way to relax this constraint but I would rather not expose my extension to XSS attacks. For now 3.0 works fine for my needs, but it would be nice to get updates in the future. Would it be possible to replace these assignments with your webpack build process for each environment? So the web version would have `var global = window;` and `var global = self;` in web worker etc.

**Comment by jpatel531** [comment]
Ah yes, that makes a lot of sense. The reason I chose the eval was to provide a cross platform way to retrieve globals. I was unaware of this particular use case, but it is definitely a valid one. I'll definitely try and bring a new method of introducing globals for future releases. I'll leave this open for reference. Thanks for mentioning this!

**Comment by jpatel531** [comment]
And with webpack I definitely think it's possible to add a loader for this. for the web build it will reference window. for workers, self. node, global. for react-native i might have to keep with the eval statement, but maybe there's a way which i haven't found yet

**Comment by georgehenderson** [comment]
Great. Webpack makes this easily work with the Define plugin or loader. Thanks for considering the change.

**Comment by newchloe18** [comment]
+1

**Comment by sandstrom** [comment]
Have a look here: https://github.com/davidchambers/Base64.js/blob/master/base64.js

**Comment by jpatel531** [comment]
I'm on it now. Sincere apologies for the delay - it's been a busy time!

**Comment by sandstrom** [comment]
Awesome!

**Comment by jpatel531** [comment]
Released in 3.2!

**Comment by yarcub** [comment]
Still having CSP issues on a Chrome App due to this line on 3.2.0:
https://github.com/pusher/pusher-js/blob/master/dist/web/pusher.js#L933

Any reason to not change those occurrences on other modules (e.g. [timer](https://github.com/pusher/pusher-js/blob/master/src/core/utils/timers/index.ts#L5))?

**Comment by jpatel531** [comment]
Ah no - that was just a silly human error

**Comment by jpatel531** [comment]
https://github.com/pusher/pusher-js/pull/188/commits/368d65cc2b3b66edd441ecf476f2c5831b3769a8

this should rectify this. I'll get out a patch asap

**Comment by yarcub** [comment]
Awesome @jpatel531. 🙇

**Comment by jpatel531** [comment]
3.2.1 is on npm and on the CDN as 3.2.1. It will be under 3.2 tomorrow

**Comment by yarcub** [comment]
3.2.1 works in Chrome Apps now. Thanks!

**Comment by jackfranklin** [comment]
@yarcub awesome!

**Comment by augustoclaro** [comment]
seems like this problem is back on version 3.2.4

`Refused to load the script 'https://timeline47-clientstats1.pusher.com/timeline/v2/jsonp/2?session=MTU1ODk5NzI5&bundle=Mg%3D%3D&key=MmFkZWQ0Y2M0Mjg4Mjg4MWQ5ZDg%3D&lib=anM%3D&version=My4yLjQ%3D&features=WyJ3cyJd&timeline=huge_hash_removed' because it violates the following Content Security Policy directive: "script-src 'self' 'unsafe-inline' 'unsafe-eval' https://apis.google.com https://www.gstatic.com https://www.google-analytics.com https://*.pendo.io https://stats.pusher.com https://cdn.embedly.com https://fast.wistia.net https://pendo-static-xxxxx.storage.googleapis.com https://timeline45-clientstats1.pusher.com https://js.intercomcdn.com https://widget.intercom.io". Note that 'script-src-elem' was not explicitly set, so 'script-src' is used as a fallback.
`
is there any fix coming up?
