### ISSUE TITLE
Pusher reconnect after window suspension fails to authenticate

### ISSUE THREAD

**Issue by danieldonev** [pusher/pusher-js#190]
The case: 
I am using pusher and as long as I am keeping the browser open on the screen - it is ok. 
Then I put my computer to sleep and do another work for 11 min (auth token time out is 10). Then when I come back - the Pusher fails to authenticate.

Reason: That is happening because the token is old (that is understandable), and there is NO fallback method which can be called when the server responses with error when trying to authenticate.

Question: can you please explain to me how to solve that problem.

Edit: it is not possible to change the token after it was added already

```
var client = new Pusher(key,
                        {
                            cluster: cluster,
                            encrypted: true,
                            authEndpoint: pusherEndPointAuth,
                            auth: {
                                headers: {
                                    "Authorization": "Bearer " + getAccessToken()
                                }
                            }
                        });
```

**Comment by hph** [comment]
@danieldonev Sorry for responding so late but you should be able to handle the error by fetching a new token and retrying.

**Comment by pietro909** [comment]
@hph I have this issue, but how should I use the new token?

Currently, the only thing I've found is that I might be able to use `socket.config.auth.headers.Authorization = `Bearer ${new_token}` but the question is: is this the official way? Sounds very hackish.

**Comment by hph** [comment]
At the moment, the least error prone way of doing it would be to re-instantiate the Pusher object (`socket` in your case). Although I haven't tried your method, I would expect it to work as well. What would be the optimal API for dealing with this, in your opinion?

**Comment by pietro909** [comment]
The good news is that the direct assignment works 👍 

> the least error-prone way of doing it would be to re-instantiate the Pusher object 

Agree, although it requires some refactoring at least on our codebase.

> What would be the optimal API for dealing with this

good question... since it is stateful, re-instantiation is the best approach to cope with a mutation. But at that point would be also better to expose the config in read-only mode.

What about a setter for that property like `socket.setToken(newToken)`? I'm not a fan of setters, on the other hand, is still better than having a public mutable state in my opinion.

Thanks!

**Comment by pietro909** [comment]
@hph this step is unclear to me:

> you should be able to handle the error by fetching a new token and retrying

I suppose you mean something like this:

    function openPrivateChannel(name) {
        let channel = socket.subscribe(name)
        channel.bind("pusher:subscription_error", code => {
            const newToken = getAValidToken()
            socket.config.auth.headers.Authorization = `Bearer ${new_token}`
            openPrivateChannel(name) // never executed, apparently
        })
    }

Where in case of failure I update the authorization token and then try again.
This code is not working as expected though since all I see is the first failure and then it looks like the second try is not executed.

My code is more complex but it boils down to what I wrote above. What am I missing?

Thanks!
