### ISSUE TITLE
'failed' connection state is not triggered

### ISSUE THREAD

**Issue by zinkkrysty** [pusher/pusher-js#21]
When I test my application in IE with flash disabled, the 'failed' connection state is not triggered, which doesn't allow me to display a sympathy message for my users that don't have Flash (or wrong version) or WebSockets. 

The code I was using at the beginning is this:

``` js
pusher.connection.bind('failed', function() {
  alert('not supported');
});
```

And when I was trying to debug a little further I tried to bind the 'state_change' event:

``` js
pusher.connection.bind('state_change', function(states) {
  // states = {previous: 'oldState', current: 'newState'}
  alert("Pusher's current state is " + states.current);
});
```

Which does what is suppose in Safari or IE with Flash but doesn't output anything in IE without Flash.

Does anyone have a working example that the 'failed' state is triggered?

**Comment by jesussobrino** [comment]
Hello!

I have exactly the same problem. I can read in docs (https://pusher.com/docs/client_api_guide/client_connect) I should bind 'error'

So I do the following: 

 pusher.connection.bind('error', function (error) {
          console.log('Service error');
        });

        pusher.connection.bind('failed', function (error) {
          console.log('service failed');
        });

        pusher.connection.bind('state_change', function(states) {
          console.log("Pusher's current state is " + states.current);
        });

And when I connect / disconnect my internet connection the only console log I can see is "Pusher's current state is ...". Should I do something else?

Thanks in advance!

**Comment by leggetter** [comment]
From https://pusher.com/docs/client_api_guide/client_connect:

A state of `failed` means:

> Pusher is not supported by the browser. This implies that WebSockets are not natively available, Flash is not available, and an HTTP-based transport could not be found.

This will only every happy at the very start of the connection/`Pusher` instantiation process.

A state of `error` occurs:

> When connection limits are reached additional connections over the limit will be rejected

Additionally, this may happen if you provide the incorrect application key. This also only happens at the very start of the connection/`Pusher` instantiation process.

> when I connect / disconnect my internet connection the only console log I can see is "Pusher's current state is ..."

As above, this is because both `failed` and `error` are initial failure states and you shouldn't expect to see them during the reconnection cycle.

I hope this clarifies things.
