### ISSUE TITLE
Having multiple instance of pusher

### ISSUE THREAD

**Issue by abelski21** [pusher/pusher-js#217]
I'm working on a widget code that uses pusher-js to get realtime updates from the server. This widget is embeddable in a client and while working on a test page, I see multiple pusher instance created every time we call the widget code method. I know it's wrong to create a new pusher instance without disconnecting to the previous one. I'm just using the same pusher key and I don't know how to remove/disconnect the page from the pusher connection before creating a new instance. My page shouldn't need to reload/refresh to load the widget code.

Here's the scenario of my widget code: (for better understanding)

 - we call the widget code using `<script>` tag
 - once it's loaded, we call a init() method to pass some configurations to authenticate the client.
 - Once the client has been authenticated, I call the pusher init method that initializes the pusher connection:

    PUBSUB._pusher = new Pusher(key, options);

The problem is that we use to click a button to submit the configurations and load that widget which will initialize another pusher connection with the same key. Now I'm getting multiple same events from those connections. I'm trying to call `PUBSUB._pusher.disconnect()` before creating another pusher instance but it will return undefined since PUBSUB._pusher has no value. I see in my chrome's network tab that I have multiple websocket connections. 

How will I disconnect from those websocket connection before initializing another one?

**Comment by hot-leaf-juice** [comment]
Can you have your widget live inside some container, have the container instantiate pusher, and then just have the widget use this already existing pusher instance? This way a new instance doesn't need to be made every time your widget changes since you can keep the reference in the outer container alive.

**Comment by abelski21** [comment]
Hmm..the problem is this widget can be embeddable in other host page which I might not have any control. If I create a separate script container, the host page will still call this every time they need the widget, then it will still create another instance. Thinking if there's a way to kill all those existing same pusher connection in the browser before initializing a new one.

**Comment by hot-leaf-juice** [comment]
There's nothing inherently wrong with having multiple connections open, it just means you'll end up having more concurrent connections than is strictly necessary (for billing purposes). Do your widgets have access to each other / the global namespace? Can you load pusher in to some shared location and then reuse the existing one?

**Comment by leonardiwagner** [comment]
I was doing the very same, the problem is.. the widget connection should be different than installed widget website... there are `new Pusher()` in both widget and website, with different credentials.. the Pusher callbacks.. calls directly `window.Pusher` 

The solution is, on widget, wrap its pusher content into `<iframe url=` tag. Is also possible to wrap the the widget instead, however the widget should provide events to parent listen, such as minimize and maximize, then parent can resize the wrapper iframe on these actions.
