### ISSUE TITLE
React native testing

### ISSUE THREAD

**Issue by kyangy** [pusher/pusher-js#232]
Hey guys,

I was wondering if there were any examples or if anyone knew how to stub pusher so that I can include it in my tests. I do get this in my test console "Invariant Violation: Native module cannot be null" so I think I need to mock it somehow.

react-native: 0.42.3
jest: 19.0.2

**Comment by GVanderLugt** [comment]
@kyangy Did you end up figuring this out?

**Comment by hph** [comment]
Hi @kyangy and @GVanderLugt. I don't have a lot of experience with React Native myself but I've used Jest quite a bit. In order to use it with React Native it looks like you have to configure a preset, as shown [here](https://facebook.github.io/jest/docs/en/tutorial-react-native.html). You can then either use the library directly or [mock it](https://facebook.github.io/jest/docs/en/manual-mocks.html). Please do let me know if there's anything specific to pusher-js failing that I missed.
