### ISSUE TITLE
React Native Websocket Issue

### ISSUE THREAD

**Issue by kelvinaliyanto** [pusher/pusher-js#234]
Hi, I am using pusher with react-native, and in some occurrences, it crashed because of the following problem that I retrieved from Crashlytics:

> Fatal Exception: java.lang.RuntimeException: Cannot send a message. Unknown WebSocket id 46
>        at com.facebook.react.modules.websocket.WebSocketModule.send(WebSocketModule.java:212)
>        at java.lang.reflect.Method.invoke(Method.java)
>        at com.facebook.react.bridge.BaseJavaModule$JavaMethod.invoke(BaseJavaModule.java:318)
>        at com.facebook.react.cxxbridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:158)
>        at com.facebook.react.bridge.queue.NativeRunnable.run(NativeRunnable.java)
>        at android.os.Handler.handleCallback(Handler.java:739)
>        at android.os.Handler.dispatchMessage(Handler.java:95)
>        at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:31)
>        at android.os.Looper.loop(Looper.java:234)
>        at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:196)
>        at java.lang.Thread.run(Thread.java:818)

After tracing the stack thoroughly, I conclude that this problem was due to Pusher, as Pusher is also the only WebSocket that I use. But I cannot find the cause and solution. Please help. Thanks.

**Comment by hph** [comment]
@kelvinaliyanto The Pusher library is written in TypeScript and compiled to JavaScript. React Native provides the WebSocket API that you see in the snippet above, and Pusher only uses it indirectly. You should probably publish a bug report on the React Native bug tracker instead. There's not much I can do myself, unfortunately. Please do reference this issue in the issue you open on the React Native issues tracker, so that other people can benefit from it. Thanks!

**Comment by yedidyak** [comment]
@kelvinaliyanto did you open an issue in react-native for this or find out any reason for it?

**Comment by robertherber** [comment]
I’ve also seen an occurrence of this when using Pusher. Any updates?

**Comment by rodrigobdz** [comment]
@robertherber @kelvinaliyanto @yedidyak any updates on the issue?
There is an issue in [react-native](https://github.com/facebook/react-native/issues/14527) regarding this problem but was closed due to missing reproduction steps.

**Comment by robertherber** [comment]
@rodrigobdz It's only occurred once for over 6000 users in my case, so I don't have much context to bring to the table I'm afraid. At this point I won't put more time into it.

**Comment by JaxGit** [comment]
@kelvinaliyanto @robertherber @rodrigobdz @yedidyak 
I only encountered this error on Android, RN 0.51; it works fine on iOS.

Reason I found is because I was trying to explicitly unsubscribe channel and disconnect pusher when the user logs out, however sequenced these async tasks like:
```
this._pusher.unsubscribe(privateUserChannel);
this._userChannel = null;
this._pusher.disconnect();
this._pusher = null;
```

it seems the pusher client is still trying to send `pusher:unsubscribe` event to pusher server (according to [documented protocol sequence chart](https://pusher.com/docs/pusher_protocol#subscription-events)  ) even if `this._pusher.disconnect()` has finished first and there is no websocket left. 

Unfortunately there is no callback for `pusher.unsubscribe()` or `'pusher:unsubscription_succeeded'` event just like valid event `'pusher:subscription_succeeded'` for us to bind. 
So my hacky way to fix this is just to use setTimeout to put the disconnnect task in the next position of the queue. 
```
this._pusher.unsubscribe(privateUserChannel);
this._userChannel = null;
setTimeout(() => {
    this._pusher.disconnect();
    this._pusher = null;
}, 0);
```
