### ISSUE TITLE
Reduce initialization of Pusher connections

### ISSUE THREAD

**Issue by dzotos** [pusher/pusher-js#253]
Trying to find an optimal way to reduce the initialization of Pusher connections in our web app. 
At the moment We are in the middle of a migration, as a result to serve at the client few scripts bundled though Webpack. The thing is that we initiate two connections, one within our main bundles and another one from our main application due to different scope. So the question is, whats the best way to share one connection without expose to global namespace the connection instance and have vulnerability issues.

Also, I recently read an article about shared workers and how to reduce connections across multiple tabs https://blog.pusher.com/reduce-websocket-connections-with-shared-workers/
Is there any other suggested way to achieve this due to browser compatibility/polyfill issues.

**Comment by kn100** [comment]
Hi,

Could you clarify why specifically you're working with two Pusher instances?

**Comment by dzotos** [comment]
Hi @kn100, I managed to fix the Pusher instance duplication. What you suggest about maintaining  the connection through multiple tabs?

**Comment by hph** [comment]
Hi @dzotos. It's a bit difficult to answer how this problem might be solved without more info on the Webpack config and your application's architecture. Could you open an issue on Stack Overflow and link to it from here? You'd probably have the most success by tagging it with `webpack` as well as `pusher` and detailing why you have two bundles and how they interact.

I'm going to close this issue for now, but if it turns out to be an issue with pusher-js, feel free to reopen it!
