### ISSUE TITLE
Auth info required to subscribe to private-channel

### ISSUE THREAD

**Issue by vankerre** [pusher/pusher-js#320]
Using custom authEndPoint @ /admin/pusher/auth/ and properly handling auth with socket_auth(channel,socket) on the backend gives me a client error : 

Auth info required to subscribe to private-ci-received-1.

The backend returns the auth : key properly formatted in JSON.

Checking documentation for this specific error I managed to find nothing.

Using pusher-js and pusher-php-server.

**Comment by leesio** [comment]
Hi @vankerre ,

I'd like to keep issues in this repo limited to specific issues with the pusher-js library.

This seems like a general issue with a tutorial. If you'd still like help with this, it's better if you contact [pusher support](https://support.pusher.com/hc/en-us)

I'm going to close this issue.

**Comment by jayant-lumino** [comment]
Not sure if it's gonna help someone, but it did help me here.

In my case, the issue was that I was sending a typical API response after the authentication, which should not have been done in this case.

Pusher JS requires the channel authorization API response in a specific format. In my case, it should have been:

```
export interface ChannelAuthorizationData {
    auth: string;
    channel_data?: string;
    shared_secret?: string;
}

```

Earlier, I was sending the response like this:

```
{
    "status": true,
    "message": "Authorized successfully",
    "data": {
        "auth": "0185140b07122d1db728:2783118fdb86c9c104da0a4fc55ef715ce1b5ff596f371dff7ac51d4b14a9e42"
    }
}

```
But it should have been like this:
```

{
    "auth": "0185140b07122d1db728:cf14e3ddf7472fe1febb45ec6c10194f9a3b8a70c0f5d659a9bd586c400c9b65"
}

```

This was the only change I made, and tada! It worked.
