### ISSUE TITLE
console.log in js code is not working

### ISSUE THREAD

**Issue by monkey-qiang1994** [pusher/pusher-js#414]
Hi~
It seems that everything is normal, but why the console.log of the JS code is not output to the Console page?

![image](https://user-images.githubusercontent.com/39218201/73597303-bec8e000-452a-11ea-9daf-12ca4d021b17.png)
![image](https://user-images.githubusercontent.com/39218201/73609450-06ed0e80-45ce-11ea-95d9-41e04bb722de.png)
![image](https://user-images.githubusercontent.com/39218201/73597299-ac4ea680-452a-11ea-8cab-e8a86ee44bc6.png)

**Comment by leesio** [comment]
Hi there,
I think there's a few issues at play here:

1. `console.log` calls in the browser won't go to the channels debug console, they'll be printed in your browser's console. The channels debug console shows events that happen inside pusher.
2. The reason your event isn't printed in your browser's console is because the event you're receiving does not match the event you're binding to. You can see in the event details in your browser console:
```
Pusher : Event recd: {"event": "App\\Events\\NewOrder", "channel": "new_order", "data": {"id": 3}}
```
You've received an event: `App\\Events\\NewOrder` but you've bound to `NewOrder`.

**Comment by leesio** [comment]
I'm going to close this issue as it isn't really an issue with the pusher-js library. Feel free to check out the channels help centre if you're still having issues.
