### ISSUE TITLE
Pusher Auth 'jsonp' is not a recognized auth transport

### ISSUE THREAD

**Issue by rasu007** [pusher/pusher-js#438]
Hello,
when I try this code in React Native it throws an error 'jsonp' is not a recognized auth transport,
But when I try this on React works. I am new in Pusher. Can anyone let me know why this happens & how to solve this

var pusher = new Pusher('e5ea65a2f06400479481', { 
            authEndpoint: "https://xxxxx.xxxxxx.com/chatpusher/api/visitors/pusherAuth/xx/xxxxx",
            authTransport: 'jsonp',
            'cluster':'ap2',
});

Thanks in Advance
Rashed

**Comment by leesio** [comment]
Hi Rashed,

The JSONP authentication mechanism wont work in react-native because JSONP won't work in react-native.

https://stackoverflow.com/a/55167995/4457241

For react-native you'll need to use the default `xhr` authentication mechanism. There are some docs describing auth [here](https://www.pusher.com/docs/channels/server_api/authenticating-users)

I'm going to close this issue as I don't believe it's a problem with the library.
