### ISSUE TITLE
Typescript type errors when compiling

### ISSUE THREAD

**Issue by devloe** [pusher/pusher-js#493]
When trying to compile my project, I get tons of typing errors (I don't really know why my compiler is checking for typing errors in my node_modules packages in the first place):

For instance:

ERROR in /Users/admin/Documents/projects/wavezoo/node_modules/pusher-js/src/core/utils/collections.ts:
157:32 Parameter 'value' implicitly has an 'any' type.

Why are there variables with no typing at all?

**Comment by leesio** [comment]
Hi @devloe,

I assume you have the `noImplicitAny` param set in your typescript config? You might want to consider using the `--skipLibCheck` option as described [here](https://www.typescriptlang.org/docs/handbook/compiler-options.html)?

> Why are there variables with no typing at all?

This is because pusher-js started as a javascript project and then was migrated to typescript. Unfortunately there are still parts of the codebase that need work to improve the quality of the typings in the library.

**Comment by aymanechaaba1** [comment]
I'm getting the same error
