### ISSUE TITLE
Inconsistency between members.me.id and membes.each(member => member.id)

### ISSUE THREAD

**Issue by ChrisHSandN** [pusher/pusher-js#528]
**Do you want to request a *feature* or report a *bug*?**
Bug 

**What is the current behavior?**
When calling `console.log(typeof presenceChannel.members.me.id)` 
the returned datatype is `number`

When calling `presenceChannel.members.each(member => console.log(typeof member.id))`
The returned datatype is `string`

**If the current behavior is a bug, please provide the steps to reproduce and
if possible a minimal demo of the problem via https://jsfiddle.net or similar.**
N/A as requires server side auth to setup a presence channel.

**What is the expected behavior?**
The `id` property should be a consistent type, 

It would seem most useful if it was always a string (regardless of if it is a numeric input) to remove the issue with max integer sizes and the pain point when a mix of numeric and alphanumeric ids are used (but I guess that would be a breaking change).

**Which versions of Pusher, and which browsers / OS are affected by this issue?
Did this work in previous versions of Pusher? If so, which?**
Latest Pusher JS v7.0.3, Windows 10, Chrome 88

**Comment by ChrisHSandN** [comment]
After taking the time to report an issue in a commercial library like this; I would have hoped to get at least some more feedback than a tag of `wontfix` and a stale bot closeout 5 months later 🤔

**Comment by amad** [comment]
@ChrisHSandN thanks for reporting this issue. Somehow we missed the notification and it got automatically flagged as `wontfix` due to inactivity. Apologies for that.

That's indeed not the desired behavior. Pusher doesn't cast data to different types. What you set in your back-end is what Pusher delivers to your front-end/client.
So I looked into this but I wasn't able to reproduce it using [pusher-js v7.0.3](https://github.com/pusher/pusher-js) client library, and [pusher-http-node v5.0.0](https://github.com/pusher/pusher-http-node) server library. But, maybe you are using a different server library. Would you please specify which [server library](https://pusher.com/docs/channels/channels_libraries/libraries/#official-server-libraries) you are using? Then I can try to replicate your environment and test it again.
