### ISSUE TITLE
Pusher triggering only after the page reloads

### ISSUE THREAD

**Issue by TheAswin** [pusher/pusher-js#531]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
**_Only_** run the expected function after the page is reloaded 

**What is the expected behavior?**
When the pusher is triggered, it should run the `alert` function. But, the `alert` only runs after the page reloads ! 

     useEffect(() => {
     const pusher = new Pusher("xxxxxxxxxxxxxx", {
      cluster: "xxxxxxxx",
    });
    const channel = pusher.subscribe("xxxxxxx");
    channel.bind("xxxxxxxxxx", function (newMessage) {
      alert(newMessage);
    });
    return () => {
      channel.unbind_all();
      channel.unsubscribe();
    };
    }, [messages]);

**Which versions of Pusher, and which browsers / OS are affected by this issue?**
pusher-js: "^7.0.3"

**Comment by ben-pusher** [comment]
This behaviour is caused by one of the following scenarios: 
-Your client is not connecting to Channels correctly
-Your client is subscribing to a different channel than the events are being sent on
-Your client is binding to a different event name
-Your publishing server is not able to trigger events correctly. 

Can you please check each of the above to ensure everything is setup correctly. You can use the debug console in the Pusher Dashboard to check subscriptions and events as they happen. 

This doesn't appear to be a library issue but instead an implementation issue so if you are still encountering issues after checking the above could I request that you please contact support via https://support.pusher.com/hc/en-us/requests/new. We prefer to keep GitHub issues for library bugs.
