### ISSUE TITLE
Question: Dynamically updating the auth headers

### ISSUE THREAD

**Issue by Brenneisen** [pusher/pusher-js#617]
Hello,

so far it was possible to update the auth header after instantiation. Since v7.1.0 the global config object is no longer used and 

`pusher.config.auth.headers.Authorization = 'Bearer <access-token>';`

no longer works. Is it still possible to change the `authOptions` after instantiation?

**Comment by benw-pusher** [comment]
Hi, Thanks for sharing. The `pusher.config.auth.headers.Authorization` method for this was an internal library function that was exposed in error. Due to the changes to authentication and authorization introduced in version 7.0 this function was removed. 
We do agree that being able to change the auth options after initialisation is certainly a useful capability. 
However, at this stage we can't commit to a release or time frame for release. We advise that you use the workaround to create a custom handler that updates the headers and handles the POST request to the auth endpoint.

**Comment by ivial98** [comment]
@benw-pusher Could you elaborate more about this workaround? Maybe code example or doc reference.

**Comment by benw-pusher** [comment]
@ivial98 As part of the channelAuthorization object you can specify a customHandler function that is called instead of the normal authEndpoint POST request behaviour. Within this function you can then determine your own logic for generating an auth token, either through local generation or creating and managing a POST request to an endpoint of your choice. As you manage the request you can specify the headers as necessary. 

Hope this helps

**Comment by ivial98** [comment]
@benw-pusher Thanks. Here is my naive implementation that does not work :-(. It does Api call and get response, but do not subscribe to the channel. What function should return?

`const pusherClient = new Pusher(appKey, {
  cluster,
  channelAuthorization: {
    customHandler: async (payload) => {
      const {socketId, channelName} = payload;
      
      const body = new URLSearchParams({
        'socket_id': socketId,
        'channel_name': channelName
      });

      const response = await fetch(authEndpoint, {
          method: 'post',
          body,
          headers: {
            'Accept': 'application/json',
            'Content-Type': 'application/x-www-form-urlencoded',
            'Authorization': `Bearer ${localStorage.getItem('token')}`,
          },
      });

      return await response.json(); // {auth: '0edde9daa37669b610e2:44fcb3696d622009fa84fd35a3a8c0e12bd8fe2556e798030542e5ee419d01fd'}
    }
  }
});`

**Comment by onuragtash** [comment]
customHandler takes two parameters. First one is your payload. And second one is a callback. 

`export declare type ChannelAuthorizationCallback = (error: Error | null, authData: ChannelAuthorizationData | null) => void;
`

Just you need to trigger callback with the response of your fetch result. 

No need to return anything.

**Comment by ivial98** [comment]
So, working code for those who are using Laravel echo backend.
`const channelAuthorization = {
    customHandler: async (payload, callback) => {
        const { socketId, channelName } = payload;

        const body = new URLSearchParams({
            socket_id: socketId,
            channel_name: channelName,
        });

        try {
            const response = await fetch(authEndpoint, {
                method: 'post',
                body,
                headers: {
                    Accept: 'application/json',
                    'Content-Type': 'application/x-www-form-urlencoded',
                    Authorization: `Bearer ${getAccessToken()}`,
                },
            });

            const token = await response.json();

            callback(null, token);
        } catch (error) {
            console.log('Pusher channel auth error');

            callback(error, null);
        }
    },
};`

**Comment by Roboroads** [comment]
I have an app that is meant to be login-logout heavy while not reloading the page, where I have some keep-alive channels (not private) and some private channels that are only allowed when logged in (resubscribe after login). The page never refreshes between logging out and in. So there is a real usecase for this.

Having to create a custom handler for just changing the headers of the channelAuthorization is.. well.. You can get it's annoying :)

**Comment by Roboroads** [comment]
Why, stalebot, we added activity :(

**Comment by benw-pusher** [comment]
Not sure why Stalebot closed this...
In any case, we have now released a new version of the library that supports two new functions - `headersProvider` and `paramsProvider` - that allow you to retrieve the necessary header/param values at the time of the auth request instead of the current method of defining them at the time of instantiation. 

These functions are available in v7.6.0

**Comment by Roboroads** [comment]
Awesome! Thanks!
