### ISSUE TITLE
Unable to subscribe to channels

### ISSUE THREAD

**Issue by stesvis** [pusher/pusher-js#627]
**Do you want to request a *feature* or report a *bug*?**
Bug (?)

**What is the current behavior?**
I am subscribing to a channel in React but the response always says `subscribed: false`.

LOGS:
Pusher :  : ["State changed","initialized -> connecting"]
Pusher :  : ["Connecting",{"transport":"ws","url":"wss://ws-us3.pusher.com:443/app/<xxxxxxx>?protocol=7&client=js&version=7.4.0&flash=false"}]

![image](https://user-images.githubusercontent.com/6062684/185715068-90c57ac0-b476-4c28-af2f-898ec4b38b01.png)

**If the current behavior is a bug, please provide the steps to reproduce and
if possible a minimal demo of the problem via https://jsfiddle.net or similar.**

```js
  useEffect(() => {
    if (!currentUser) return;

    Pusher.logToConsole = true;

    const pusher = new Pusher(process.env.REACT_APP_PUSHER_APP_ID, {
      cluster: process.env.REACT_APP_PUSHER_APP_CLUSTER,
    });
    const channel = pusher.subscribe(`login-notification.${currentUser?.id}`);
    console.log("channel", channel);
    channel.bind("LoginNotificationEvent", function (data) {
      console.log("login-notification data", data);
      // Code that runs when channel1 listens to a new message
    });

    return () => {
      pusher.unsubscribe(`login-notification.${currentUser?.id}`);
    };
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);
```

**What is the expected behavior?**
I'd expect to be subscribed, `subscribed: true`

**Which versions of Pusher, and which browsers / OS are affected by this issue?
Did this work in previous versions of Pusher? If so, which?**
I never used Pusher before, the version is `^7.4.0`

I've tried my best to look at the documentation + tons of examples but I can't get it to work from React.

The backed is made in Laravel.

**Comment by benw-pusher** [comment]
Hi, 
I believe this could be being caused by inspecting the `subscribed` value immediately after the subscription attempt - before the value is updated. If you open the Pusher dashboard, select your app and open the debug console do you see connections and subscriptions show there when you run the above code?

**Comment by brada1703** [comment]
Any update on this @stesvis ? I'm having the same issue

**Comment by stesvis** [comment]
> Any update on this @stesvis ? I'm having the same issue

Nope, I made the event public and decided to handle it in the backend...

**Comment by benw-pusher** [comment]
@brada1703 do you have any further info to share on this? Have you attempted what I mentioned in my previous comment? I have been able to replicate a similar scenario, however to confirm it is the same issue It would be good to know what behaviour your Pusher debug console shows when your code is run.

**Comment by benw-pusher** [comment]
We haven't had any further info on this one so I'm not able to keep it open. I believe the issue is that inspecting the subscribed value immediately will show false, even if the subscription has been successful. This is because there is a short process to complete for the subscription to be successful. This means that although the value is returning false, the subcription will succeed and you can continue to use the channel as expected to receive events.
