### ISSUE TITLE
[suggestion] Webhooks should include socket_id

### ISSUE THREAD

**Issue by hubertnnn** [pusher/pusher-js#638]
Not sure where to put suggestions regarding the cloud service, so I am leaving it here.

**Do you want to request a *feature* or report a *bug*?**
Feature request

**What is the current behavior?**
If the same user logs in on two different devices, then there is no way to pair `member_added` to `member_removed` events.
Since my use case involves counting time, being able to pair those events would be really helpful.

**What is the expected behavior?**
Add `socket_id` field to presence events to identify which instance of the specific user's session triggered those.

**Comment by benjamin-tang-pusher** [comment]
Hi, if you have a presence member on two different devices, the second member_added and the first member_removed webhook will not be sent. This is because the member was already subscribed when the second device has connected, and the member is still subscribed (and therefore not removed yet) when the first device disconnects. This is intentional as from a member perspective, that member is still connected, even is one device has disconnected. So a socket_id won't be useful in this case, since we're not going to send a webhook for each device.

What you probably need to do instead is have an individual channel for each device. You can use a webhook for channel occupation and vacation, where the channel name corresponds to the device. Or you can have each device be its own presence user_id.

**Comment by hubertnnn** [comment]
ok, makes sense
