### ISSUE TITLE
Multi authentication

### ISSUE THREAD

**Issue by tommoor** [pusher/pusher-js#69]
Our application needs to authenticate upto 40 private channels on load, our server side auth endpoint can obviously handle this with no problem but how should it be approached from the POV of the JS library? 

I'm finding a lot of mixed information across the internet and no solid examples of how to achieve this. I don't want to have to monkey patch the client lib?

**Comment by marknadig** [comment]
@pl I see this plugin is still referenced in the docs https://pusher.com/docs/authenticating_users. Any new news on this supported in core?

**Comment by leggetter** [comment]
Hey @marknadig - this is something we'd definitely like to do, but we don't have it planned in right now. We'll certainly keep this issue open so that we can pick it up in the future.

**Comment by hph** [comment]
I'm closing "feature request" issues, including this one. This does not mean that the feature will not be implemented, we just want to reserve open GitHub issues to bugs that need to be addressed.

Feel free to comment here to keep the discussion going. People watching the repository will still receive notifications.

**Comment by thebrucecgit** [comment]
Has there been any progress in this feature yet? It seems like an important aspect of creating any chat application yet this seems to be such low-priority.

**Comment by leesio** [comment]
@thebrucecgit there hasn't been any change in the pusher-js library with respect to multi auth, a lot of people seem to be having success with the pusher-js-auth repo.
https://github.com/dirkbonhomme/pusher-js-auth

Would you be able to provide some more information on your specific use case? How many channels do you need to auth? What type of channels are they? If you don't feel comfortable sharing this info publically you can send it to support@pusher.com

**Comment by thebrucecgit** [comment]
I tried `pusher-js-auth`, but my functions binded to the events were no longer being called. I might've configured something wrong, but I thought it was because the the project looks abandoned and as noted above it's really just a

> quick hack for multi auth 

It would be great to get some official support for this. 

I am essentially trying to build a Facebook Messenger clone. You can have many different chats (I'd say maybe up to 50-100 chats?) with different groups of people, but the end-client has to receive messages for all of the chats / channels simultaneously. This means every chat has to be on a different channel and every subscription must be authenticated on the server to check if the user has the correct authorization. 

Creating my own custom WebSockets solution works for me, but it might be an issue in the future with scale.
