### ISSUE TITLE
Pusher User Authentication Endpoint and params not being overridden

### ISSUE THREAD

**Issue by exquisiteboy** [pusher/pusher-js#771]
**Do you want to request a *feature* or report a *bug*?**
report a bug
**What is the current behavior?**
params and endpoint is not using the custom provided URL and params and headers. create a new pusher instance and pass in the userauthatication params and call pusher.signin() 
**If the current behavior is a bug, please provide the steps to reproduce and
if possible a minimal demo of the problem via https://jsfiddle.net or similar.**
var pusher = new Pusher('PUSHER_APP_KEY'', {
    userAuthorization: {
      transport: "ajax",
      endpoint: "/pusher_user_auth",
      headers: {
        'Authorization': user_access_token
      },
      params:{
        'Authorization': user_access_token
      }
    },
    cluster:'PUSHER_APP_CLUSTER'
  });
  pusher.signin();
**What is the expected behavior?**
should use the custom signing to use for user authentication to presence channel
**Which versions of Pusher, and which browsers / OS are affected by this issue?
8..0.1
Did this work in previous versions of Pusher? If so, which?**

**Comment by benw-pusher** [comment]
The values used in the headers/params will be set the first time you instantiate the Pusher object. If you need to dynamically retrieve these values as they may change then you can make use of the `headersProvider` and `paramsProvider` options =- https://github.com/pusher/pusher-js/tree/ed900f8d4fc121cb2c7e20809a3cac8e3249d812#userauthentication-object. 

This allows the tokens to be retrieved at the time of the request, instead of during instantiation.

**Comment by ahmetkca** [comment]
> The values used in the headers/params will be set the first time you instantiate the Pusher object. If you need to dynamically retrieve these values as they may change then you can make use of the `headersProvider` and `paramsProvider` options =- https://github.com/pusher/pusher-js/tree/ed900f8d4fc121cb2c7e20809a3cac8e3249d812#userauthentication-object.
> 
> This allows the tokens to be retrieved at the time of the request, instead of during instantiation.

How does this answers his question? I am facing with the same problem. Pusher is trying to use `/pusher/user-auth` isntead of custom passed endpoint `/api/pusher/user-auth`?

**Comment by AndreSilva1993** [comment]
> The values used in the headers/params will be set the first time you instantiate the Pusher object. If you need to dynamically retrieve these values as they may change then you can make use of the `headersProvider` and `paramsProvider` options =- https://github.com/pusher/pusher-js/tree/ed900f8d4fc121cb2c7e20809a3cac8e3249d812#userauthentication-object.
> 
> This allows the tokens to be retrieved at the time of the request, instead of during instantiation.

@benw-pusher  Any way the `headersProvider` could allow aysnc functions? Right now I'm trying to obtain fresh JWT tokens whenever Pusher needs to re-authorize and the function is almost unusable since I can't `await` something in here. Would pretty much like to avoid intervals that update a local variable.

**Comment by sajcics** [comment]
facing the same issue. custom endpoint for private channel is never called by pusher.

**Comment by jhleao** [comment]
I was able to fix this by changing

```typescript
const pusher = new Pusher(appKey, {
  userAuthentication: {
    endpoint: '/api/pusher-auth',
    transport: 'ajax',
  },
});
```

to 

```typescript
const pusher = new Pusher(appKey, {
  cluster: 'sa1',
  authEndpoint: '/api/pusher-auth'
});
```

Unsure if this comes from outdated documentation or else. Either way type definition accept either and only the latter works.

**Comment by jhleao** [comment]
In my case, this was happening because apparently Pusher has two separate authentication procedures… one is authenticating a subscription to a private channel (which fires when you call `pusher.subscribe()`) and another to handle user authentication, which fires when you call `pusher.signin()`.

So configuration must look something like this: 

```typescript
const pusher = new Pusher(appKey, {
  userAuthentication: {
    endpoint: '/api/pusher/auth/user',
    transport: 'ajax',
  },
  authEndpoint: '/api/pusher/auth/channel',
});
```

Not sure if this separation is documented anywhere. At least I couldn’t get this from docs.

**Comment by bxclib2** [comment]
Who closed this? I meet the same issue. The doc sucks. I read the doc many times and I still cannot understand how to pass those parameters. I don't understand why this issue is closed.
