### ISSUE TITLE
{     "type": "PusherError",     "data": {         "code": null,         "message": "Missing parameter: data.user"     } }

### ISSUE THREAD

**Issue by exquisiteboy** [pusher/pusher-js#776]
**Do you want to request a *feature* or report a *bug*?**
bug
**What is the current behavior?**
sending user data but not able to use after the auth
**If the current behavior is a bug, please provide the steps to reproduce and
if possible a minimal demo of the problem via https://jsfiddle.net or similar.**
use the pusher.signin and then after the authorization response the message comes ups 
**What is the expected behavior?**
must work to listen for other events as well 
**Which versions of Pusher, and which browsers / OS are affected by this issue?
Did this work in previous versions of Pusher? If so, which?**

**Comment by benw-pusher** [comment]
"the message comes ups" 
Can you share what message you are referring to? 

Can you also share more about your implementation so I can review - if possible please include code and errors.

**Comment by nicitaacom** [comment]
You got this error because you didn't pass data in tried parameter 
![image](https://github.com/pusher/pusher-js/assets/39565703/f1c24e87-a680-4613-be6c-1fb74b0b7d69)


![console-log](https://i.imgur.com/Nuiyckn.png)

I recommend you to create messenger-clone
Steps:
1. Go to youtube.com
2. In searchbar write 'code with Antonio'
3. in 'Videos' choose messenger-clone and build it with this guide

**Comment by benw-pusher** [comment]
We haven't had any response from the OP so closing here. 
Thanks for your help @nicitaacom
