### ISSUE TITLE
Pusher Handshake error with no further explanation

### ISSUE THREAD

**Issue by awsmsrc** [pusher/pusher-js#90]
Im working on a new feature branch on an application and haven't really changed any logic I can think of that would affect pusher connection instantiation but on this branch I have the following issue

I get the following logs in my console which repeat

```
application.a8a3df79f2be3a77.js:35453: Pusher : Error : {"type":"HandshakeError","error":{}} 
application.a8a3df79f2be3a77.js:10858: ["pusher", "Pusher : Error : {"type":"HandshakeError","error":{}}"] 
```

until I manually call 

```
pusher.disconnect();pusher.connect();
```

Which gets everything going as expected

I realize this is vague but if you have any ideas of what to look for or want me to provide specific information I can do that

Cheers in advance

**Comment by Sapphire64** [comment]
Hi @pl, I had the same problem yesterday with Pusher. Here is the code sample:
```
    pusher.connection.bind('connected', function() {
      return tide.actions.pusher.handleConnectionEstablished();
    });
```
The problem was that `handleConnectionEstablished` was crashing. The only output I had in console was the same: 
```
Pusher : Error : {"type":"HandshakeError","error":{}} 
```
Lack of errors output may be explained by some promises happening in that handler, but still there is an odd message from pusher which makes not much sense.

**Comment by pl** [comment]
Hi @Sapphire64,

Thanks for reporting, this is a known problem and I've written a patch to fix this issue, but we haven't merged it yet: https://github.com/pusher/pusher-js/pull/105

I am not actively maintaining the library at the moment, but I'll raise the issue in the team :)
