### ISSUE TITLE
Chrome Apps support

### ISSUE THREAD

**Issue by xcrespo** [pusher/pusher-js#96]
Chrome Apps have some differences with respect to traditional web apps. For instance, managing local storage or web sockets have a native implementation. 

Since this library can't be used in this apps, do you have any alternative js library which supports Chrome apps?

**Comment by pl** [comment]
Hi Xabi,

I don't think we have a library that runs in Chrome Apps. Local storage is not a problem, it's an optional optimization that's skipped when `window.localStorage` is not available. It doesn't seem like Chrome App environment supports WebSockets or XMLHttpRequest - if it did, you could use one of the existing transports.

One way to go is to experiment with providing a WebSocket or XMLHttpRequest polyfill and see if existing transports work or write a new transport basing on built-in sockets, but I can't guarantee there are no other incompabilities in pusher-js as I have no experience with Chrome Apps.

**Comment by azap23** [comment]
xcrespo,

Not sure if this will help you out, but i am building a chrome app where i want to use pusher-js.  When i first tried to do so i was getting 3 errors.  The first two were about window.localStorage not being available.  I got rid of those by editing the pusher-js script replacing the windows.localStorage reference with chrome.storage.local.

The third error was:
Refused to load the script 'http://stats.pusher.com/timeline/v2/jsonp/1?session=NzA4NDU1Mjc2&bundle=MQ%…Y2tldF9pZCI6IjQzNjgzLjM1MDk5OTAifSwidGltZXN0YW1wIjoxNDIzNTExNDQ1ODU5fV0%3D' because it violates the following Content Security Policy directive: "default-src 'self' chrome-extension-resource:". Note that 'script-src' was not explicitly set, so 'default-src' is used as a fallback.

To get around this error i used the disableStats option when creating my Pusher object.

var pusher = new Pusher('api-key', { disableStats: true });

After that everything seems to be working without any issues.

**Comment by xcrespo** [comment]
@azap23 I was looking for an official library so we wouldn't have to maintain the updates. In the meanwhile we will use your solution as a workaround. Thank you!

**Comment by pl** [comment]
@azap23 thanks for the info - I'm surprised you get localStorage errors, since all calls are wrapped in try-catch blocks and they are not required for pusher-js to work. Maybe we should introduce a flag to disable transport caching, so that code wouldn't get executed at all.

Good to hear that pusher-js works for Chrome apps after disabling stats.

**Comment by paxal78** [comment]
my solution:
```javascript

Pusher.Util.getLocalStorage = function() {
    return undefined;
}
Pusher.ScriptRequest.prototype.send = function(receiver) {
    var xhr = new XMLHttpRequest();
    xhr.open("GET", this.src, true);
    xhr.send();
}


var pusher = new Pusher('xxxxxxxxxx', {
    encrypted: true
});

```

**Comment by edwardotis** [comment]
Add this line to you manifest.json in to fix the issue and support pusher stats:

`  "content_security_policy": "script-src 'self' https://js.pusher.com https://stats.pusher.com; object-src 'self'",
`

**Comment by sentiasa** [comment]
@edwardotis The CSP you shared was working for me until 1-2 weeks ago, but recently stopped working (I think upgrading to Chrome 65).

Now I started receiving these errors:
> WebSocket connection to 'wss://ws-{pusherId}.pusher.com/app/aae7320263d9626a6429?protocol=7&client=js&version=4.1.0&flash=false' failed: Error in connection establishment: net::ERR_NAME_NOT_RESOLVED

>OPTIONS https://sockjs-{pusherId}.pusher.com/pusher/app/aae7320263d9626a6429/412/0du6seh0/xhr_streaming?protocol=7&client=js&version=4.1.0&t=1522495955875&n=1 net::ERR_NAME_NOT_RESOLVED

I also tried loosen the policy even more with:
`"content_security_policy": "script-src 'self' 'unsafe-eval' https://www.mywebsite.com https://*.pusher.com; object-src 'self'; connect-src https://www.mywebsite.com wss://*.pusher.com https://*.pusher.com",`

Does your one work or stopped working too?
